name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: Test on Linux - ${{ matrix.swift-image }}
    strategy:
      matrix:
        swift-image:
          - "swift:6.1-jammy"
          - "swift:6.1-noble"
          - "swift:6.2-jammy"
          - "swift:6.2-noble"
    runs-on: ubuntu-latest
    container: ${{ matrix.swift-image }}
    services:
      valkey:
        image: valkey/valkey:8.0
    env:
      VALKEY_HOSTNAME: valkey
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test
